name: Build and Tests ContosoUniversity Solution
run-name: ${{ github.actor }} starts Build and Tests workflow

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'ContosoUniversity/**'

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: |
          dir
          cd $GITHUB_WORKSPACE
          dir
          cd ContosoUniversity
          dir

      - name: Restore Packages
        run: nuget restore ContosoUniversity.sln

      - name: Build Solution
        run: |
          msbuild.exe ContosoUniversity.sln /p:platform="Any CPU" /p:configuration="Debug"
        
      - name: Run Tests
        run: vstest.console.exe .\ContosoUniversity\**.Tests.dll

